-- Author: Joshua Loesch
-- UTEID: jdl3876

-- This PL/SQL block will drop a table if it exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Customers';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Cards';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE TABLE Cards (
    card_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY UNIQUE,
    last_name VARCHAR(30) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    middle_name VARCHAR(30),
    address_line_1 VARCHAR(30) NOT NULL,
    address_line_2 VARCHAR(30),
    cc_id CHAR(3) NOT NULL,
    expiration_date DATE NOT NULL,
    card_number VARCHAR(30) NOT NULL,
    card_type CHAR(4) NOT NULL
);
/

-- Creating the customer table
-- The generated statement will create an incremental ID for each insert
CREATE TABLE Customers ( 
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY UNIQUE,
    card_id NUMBER NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    middle_name VARCHAR(30),
    email VARCHAR(30) NOT NULL UNIQUE,
    address_line_1 VARCHAR(30) NOT NULL,
    address_line_2 VARCHAR(30),
    state_abbr CHAR(2) NOT NULL,
    zip_code CHAR(5) NOT NULL,
    phone CHAR(12),
    current_credits NUMBER DEFAULT (0),
    life_time_credits NUMBER DEFAULT (0),
    CONSTRAINT Card_fk_Customer FOREIGN KEY (card_id) REFERENCES Cards (card_id),
    CONSTRAINT email_length_check CHECK (LENGTH(email) >= 7),
    CONSTRAINT credits_verify CHECK (current_credits <= life_time_credits)
);
/

CREATE TABLE Reservations (
    reservation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY UNIQUE,
    location_id NUMBER NOT NULL,
    room_id NUMBER NOT NULL,
    discount_id NUMBER,
    status CHAR(1) NOT NULL,
    rating NUMBER,
    notes VARCHAR(200),
    reservation_total NUMBER NOT NULL,
    date_time DATE DEFAULT SYSDATE NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    credits_used 
);
/
